config/routes.rb
Rails.application.routes.draw do
  get 'compass', to: 'compass_sample#index'
  root to: 'top#index'

end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/compass_sample_controller.rb
class CompassSampleController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/compass_sample/index.html.slim
h1 Compass Sample

.image.test1

.image.test2

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title CompassRailsTutorial
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      .header
        .logo-wrapper
          img.logo src='' alt='Title logo'
      .wrapper
        #menu
          input#humberger-menu.switch type='checkbox'
          ul#menu-inner
            li
              = link_to 'top', root_path
            li
              = link_to 'compass', compass_path
            li
              = link_to 'compass', compass_path
            li
              label.close-button.link for='humberger-menu' = raw('&times;')
          = link_to '#humberger', id: 'humberger' do
            label.link for='humberger-menu' ≡
        #main
          = yield
    .footer
      p Copyright © 2015 masa0x80

app/views/top/index.html.slim
h1 Top Page